"""
Service for publishing PRGuard reviews to GitHub.

This service takes the findings generated by the AI review system
and publishes them as a GitHub pull request review.

The review can contain:
    - A summary of all findings.
    - Inline comments on specific lines.
    - An approval, comment, or change request.
"""

import logging
from typing import Any

import httpx

from app.github.client import GitHubClient
from app.models.review import Finding, Review
from app.review.validator import ValidatedFinding, ValidationStatus

logger = logging.getLogger(__name__)


class ReviewPublishingService:
    """
    Publishes PRGuard review results to GitHub.

    The service:
        1. Builds a review summary.
        2. Builds inline comments.
        3. Decides the GitHub review event.
        4. Sends the review to GitHub.
    """

    def __init__(self, installation_id: int):
        """
        Create the review publishing service.

        Args:
            installation_id: GitHub App installation ID used to authenticate.
        """
        self.github_client = GitHubClient(installation_id)

    async def __aenter__(self):
        """Allow the service to be used with 'async with'."""
        return self

    async def __aexit__(self, *args):
        """Close the GitHub client when the service is finished."""
        await self.github_client.close()

    async def publish_review(
        self,
        owner: str,
        repository_name: str,
        pull_request_number: int,
        review: Review,
        findings: list[Finding],
        *,
        head_sha: str,
        validated_findings: list[ValidatedFinding] | None = None,
    ) -> dict[str, Any]:
        """
        Publish a complete PRGuard review to GitHub.

        The review contains:
            - A summary message with category breakdown.
            - Inline comments for findings with a file and line.
            - A GitHub review event.

        Review event rules:
            - critical/high finding → REQUEST_CHANGES
            - medium/low finding    → COMMENT
            - no findings           → APPROVE

        Args:
            owner: GitHub repository owner.
            repository_name: GitHub repository name.
            pull_request_number: Pull request number.
            review: PRGuard review record.
            findings: Findings generated by the AI agents.
            head_sha: Commit SHA where the review comments should be placed.
            validated_findings: Optional validated findings with metadata.

        Returns:
            GitHub API response for the created review.
        """
        # Build review summary
        summary_body = self._build_summary(review, findings, validated_findings)

        # Build inline comments with validation metadata.
        # When several validated findings share the same (file, line),
        # keep the most useful one: a valid finding always wins over an
        # invalid one, then higher confidence wins.
        inline_comments = []
        validated_map: dict[tuple[str, int | None], ValidatedFinding] = {}
        for v in validated_findings or []:
            key = (v.file_path, v.line_number)
            existing = validated_map.get(key)
            if existing is None:
                validated_map[key] = v
                continue
            better = (
                (v.is_valid, v.confidence)
                > (existing.is_valid, existing.confidence)
            )
            if better:
                validated_map[key] = v

        for finding in findings:
            if not finding.file_path or not finding.line_number:
                continue

            # Find matching validated finding
            vf = validated_map.get((finding.file_path, finding.line_number))

            # Skip invalid findings
            if vf and not vf.is_valid:
                logger.debug(
                    "Skipping invalid finding: %s (status: %s)",
                    finding.title,
                    vf.validation_status,
                )
                continue

            comment_body = self._build_inline_comment(finding, vf)
            inline_comments.append({
                "path": finding.file_path,
                "line": finding.line_number,
                "body": comment_body,
                "side": "RIGHT",
            })

        # Decide GitHub review event
        review_event = self._get_review_event(findings)

        # Publish review to GitHub. If GitHub rejects the payload because
        # an inline comment points at a line it will not accept (HTTP 422),
        # retry with the summary only so the developer still gets feedback.
        try:
            result = await self.github_client.create_pull_request_review(
                owner=owner,
                repository=repository_name,
                pull_request_number=pull_request_number,
                body=summary_body,
                event=review_event,
                comments=inline_comments or None,
            )
            posted_comments = len(inline_comments)
        except httpx.HTTPStatusError as error:
            status_code = error.response.status_code
            if status_code != 422 or not inline_comments:
                logger.error(
                    "Failed to publish review on PR %s/%s#%d: %s",
                    owner,
                    repository_name,
                    pull_request_number,
                    error,
                )
                raise

            logger.warning(
                "GitHub rejected inline comments (422) on PR %s/%s#%d; "
                "retrying with summary only. Response: %s",
                owner,
                repository_name,
                pull_request_number,
                error.response.text[:500],
            )
            summary_body += (
                "\n\n> ⚠️ Some inline comments could not be attached to "
                "their lines and were omitted. See the findings list above."
            )
            result = await self.github_client.create_pull_request_review(
                owner=owner,
                repository=repository_name,
                pull_request_number=pull_request_number,
                body=summary_body,
                event=review_event,
                comments=None,
            )
            posted_comments = 0

        logger.info(
            "Published %s review on PR %s/%s#%d (%d findings, %d inline comments)",
            review_event,
            owner,
            repository_name,
            pull_request_number,
            len(findings),
            posted_comments,
        )

        return result

    # ------------------------------------------------------------------------
    # Review event
    # ------------------------------------------------------------------------

    def _get_review_event(self, findings: list[Finding]) -> str:
        """
        Decide which GitHub review event should be used.

        Rules:
            - critical/high → REQUEST_CHANGES
            - any other     → COMMENT
            - no findings   → APPROVE

        Returns:
            GitHub review event name.
        """
        has_critical = any(f.severity == "critical" for f in findings)
        has_high = any(f.severity == "high" for f in findings)

        if has_critical or has_high:
            return "REQUEST_CHANGES"
        if findings:
            return "COMMENT"
        return "APPROVE"

    # ------------------------------------------------------------------------
    # Review summary
    # ------------------------------------------------------------------------

    def _build_summary(
        self,
        review: Review,
        findings: list[Finding],
        validated_findings: list[ValidatedFinding] | None = None,
    ) -> str:
        """
        Build an enhanced review summary with category breakdown.

        Enhanced format:
        - Severity counts with emoji indicators
        - Category breakdown (security, correctness, quality, etc.)
        - Validation status summary (if available)

        Returns:
            Markdown-formatted review summary.
        """
        if not findings:
            return "## ✅ PRGuard Review\n\nNo issues found. LGTM! 🎉"

        # --- Severity breakdown ---
        severity_counts: dict[str, int] = {}
        for finding in findings:
            severity = finding.severity
            severity_counts[severity] = severity_counts.get(severity, 0) + 1

        severity_emojis = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🟢",
        }
        severity_order = ["critical", "high", "medium", "low"]

        # --- Category breakdown ---
        category_counts: dict[str, int] = {}
        for finding in findings:
            category_counts[finding.category] = category_counts.get(
                finding.category, 0
            ) + 1

        category_emojis = {
            "security": "🛡️",
            "correctness": "🔍",
            "quality": "✨",
            "error_handling": "⚠️",
            "testing": "🧪",
            "performance": "⚡",
        }

        # --- Build summary ---
        lines = ["## 🤖 PRGuard Review\n"]

        # Finding count
        lines.append(f"**{len(findings)} finding(s)** found:\n")

        # Severity breakdown
        for severity in severity_order:
            count = severity_counts.get(severity, 0)
            if count:
                emoji = severity_emojis.get(severity, "❓")
                lines.append(f"- {emoji} **{severity.title()}**: {count}")

        # Category breakdown
        if category_counts:
            lines.append("\n### Categories\n")
            for category, count in sorted(
                category_counts.items(), key=lambda x: -x[1]
            ):
                emoji = category_emojis.get(category, "📋")
                label = category.replace("_", " ").title()
                lines.append(f"- {emoji} **{label}**: {count}")

        # Validation summary (if available)
        if validated_findings:
            valid_count = sum(1 for v in validated_findings if v.is_valid)
            invalid_count = len(validated_findings) - valid_count
            if invalid_count > 0:
                lines.append("\n### Validation\n")
                lines.append(f"- ✅ {valid_count} findings verified")
                lines.append(
                    f"- ⚠️ {invalid_count} findings filtered "
                    f"(hallucination prevention)"
                )

        # Footer
        lines.append("\n---")
        lines.append("*Powered by PRGuard — AI Code Review*")

        return "\n".join(lines)

    # ------------------------------------------------------------------------
    # Inline comment
    # ------------------------------------------------------------------------

    def _build_inline_comment(
        self,
        finding: Finding,
        validated_finding: ValidatedFinding | None = None,
    ) -> str:
        """
        Build an enhanced GitHub inline comment for one finding.

        Enhanced format:
        - Severity badge + title
        - Description
        - Evidence code block
        - Category + confidence badges
        - Validation status indicator

        Returns:
            Markdown-formatted inline comment.
        """
        # --- Severity badge ---
        severity_badges = {
            "critical": "🔴 **CRITICAL**",
            "high": "🟠 **HIGH**",
            "medium": "🟡 **MEDIUM**",
            "low": "🟢 **LOW**",
        }
        severity_badge = severity_badges.get(
            finding.severity, finding.severity.upper()
        )

        comment_lines = [f"{severity_badge} — {finding.title}\n"]

        # --- Description ---
        comment_lines.append(finding.description)

        # --- Evidence code block ---
        if finding.evidence:
            file_extension = ""
            if "." in finding.file_path:
                file_extension = finding.file_path.rsplit(".", 1)[1]
            comment_lines.append(f"\n```{file_extension}")
            comment_lines.append(finding.evidence)
            comment_lines.append("```")

        # --- Metadata badges ---
        category_label = finding.category.replace("_", " ").title()
        comment_lines.append(f"\n📂 **Category:** {category_label}")
        comment_lines.append(
            f"📊 **Confidence:** {finding.confidence:.0%}"
        )

        # --- Validation status ---
        if validated_finding:
            if validated_finding.is_valid:
                comment_lines.append("✅ **Evidence verified**")
            else:
                status_messages = {
                    ValidationStatus.FILE_NOT_IN_PR: (
                        "⚠️ File not found in PR"
                    ),
                    ValidationStatus.LINE_NOT_IN_DIFF: (
                        "⚠️ Line not in diff range"
                    ),
                    ValidationStatus.EVIDENCE_MISMATCH: (
                        "⚠️ Evidence could not be verified"
                    ),
                    ValidationStatus.LOW_CONFIDENCE: (
                        "⚠️ Low confidence after validation"
                    ),
                }
                msg = status_messages.get(
                    validated_finding.validation_status,
                    "⚠️ Validation issue",
                )
                comment_lines.append(msg)

        return "\n".join(comment_lines)