"""
GitHub webhook handler for PRGuard.

This module receives webhook events from GitHub.

For pull request events, it:

    1. Reads the request body.
    2. Verifies the GitHub HMAC signature.
    3. Reads the webhook event information.
    4. Checks whether the event should trigger a review.
    5. Starts the review pipeline in the background.
    6. Immediately returns a response to GitHub.

Supported pull request actions:

    - opened
    - synchronize
"""

import asyncio
import logging

from fastapi import APIRouter, Header, Request, status

from app.github.webhooks import verify_webhook_request


logger = logging.getLogger("prguard.webhooks")

router = APIRouter()


# ----------------------------------------------------------------------------
# In-flight review tracking
#
# Two jobs:
#   1. Keep a strong reference to every background task. asyncio only holds
#      weak references, so without this a running review can be garbage
#      collected mid-flight.
#   2. Debounce. GitHub sends `opened` then often an immediate `synchronize`,
#      and retries any delivery it thinks was slow. Without a guard each of
#      those spawns a full, concurrent review of the same PR.
# ----------------------------------------------------------------------------

_active_reviews: dict[tuple[int, str, int], "asyncio.Task[None]"] = {}

# Global ceiling on reviews executing at once in this process. Created lazily
# so it binds to the running loop. A burst of PRs otherwise fans out to N
# repo clones + N*5 LLM calls simultaneously (memory / rate-limit / DB
# connection exhaustion). Extra reviews queue on this and run when a slot
# frees.
_review_semaphore: "asyncio.Semaphore | None" = None


def _get_review_semaphore() -> "asyncio.Semaphore":
    global _review_semaphore
    if _review_semaphore is None:
        from app.core.config import settings

        _review_semaphore = asyncio.Semaphore(
            max(1, settings.MAX_CONCURRENT_REVIEWS)
        )
    return _review_semaphore


async def _installation_active(installation_id: int) -> bool:
    """True unless we have a row saying the install is suspended/deleted.

    An unknown installation is treated as active — the App clearly *is*
    installed (GitHub sent us the webhook), the worker will create the row.
    """
    from app.core.database import AsyncSessionLocal
    from app.repositories.installation_repo import InstallationRepository

    try:
        async with AsyncSessionLocal() as session:
            inst = await InstallationRepository(session).get_by_installation_id(
                installation_id
            )
        if inst is None:
            return True
        return inst.deleted_at is None and inst.suspended_at is None
    except Exception as error:  # pragma: no cover
        logger.warning("Installation-active check failed: %s", error)
        return True


def _schedule_review(
    *,
    installation_id: int,
    repo_full_name: str,
    pr_number: int,
    account_type: str,
) -> bool:
    """Schedule a background review unless one is already running for this PR.

    Returns True if a new task was scheduled, False if de-duplicated.
    """
    key = (installation_id, repo_full_name, pr_number)

    existing = _active_reviews.get(key)
    if existing is not None and not existing.done():
        logger.info(
            "Review already in progress for %s#%d — ignoring duplicate "
            "webhook.",
            repo_full_name,
            pr_number,
        )
        return False

    task = asyncio.create_task(
        run_review_in_background(
            installation_id=installation_id,
            repo_full_name=repo_full_name,
            pr_number=pr_number,
            account_type=account_type,
        )
    )
    _active_reviews[key] = task
    task.add_done_callback(lambda _t, k=key: _active_reviews.pop(k, None))
    return True


# ============================================================================
# GITHUB WEBHOOK ENDPOINT
# ============================================================================


@router.post(
    "/webhook/github",
    status_code=status.HTTP_200_OK,
)
async def handle_github_webhook(
    request: Request,
    x_github_event: str | None = Header(
        None,
        alias="X-GitHub-Event",
    ),
    x_hub_signature_256: str | None = Header(
        None,
        alias="X-Hub-Signature-256",
    ),
) -> dict[str, str | None]:
    """
    Receive and process GitHub webhook events.

    GitHub expects the webhook endpoint to respond quickly.
    Therefore, the actual PR review is started as a background task.

    Args:
        request:
            The incoming HTTP request from GitHub.

        x_github_event:
            GitHub event type, for example "pull_request".

        x_hub_signature_256:
            HMAC signature generated by GitHub.

    Returns:
        A quick acknowledgment response.
    """

    # =========================================================================
    # STEP 1: Read the raw request body
    # =========================================================================

    payload = await request.body()

    # The raw bytes are required for HMAC signature verification.
    verify_webhook_request(
        payload,
        x_hub_signature_256,
    )

    # =========================================================================
    # STEP 2: Parse the JSON payload
    # =========================================================================

    try:

        webhook_data = await request.json()

    except Exception as error:

        logger.error(
            "Failed to parse GitHub webhook JSON: %s",
            error,
        )

        return {
            "status": "error",
            "message": "Invalid JSON body",
        }

    # =========================================================================
    # STEP 3: Log the received event
    # =========================================================================

    logger.info(
        "Received verified GitHub webhook event: %s",
        x_github_event,
    )

    # =========================================================================
    # STEP 4: Get basic information from the webhook
    # =========================================================================

    action = webhook_data.get("action")

    repository_name = webhook_data.get(
        "repository",
        {},
    ).get("full_name")

    sender_username = webhook_data.get(
        "sender",
        {},
    ).get("login")

    # =========================================================================
    # STEP 5: Check whether this is a PR review event
    # =========================================================================

    should_start_review = (
        x_github_event == "pull_request"
        and action in ("opened", "synchronize", "reopened")
    )

    if should_start_review:

        # =====================================================================
        # STEP 6: Get PR information
        # =====================================================================

        pull_request_number = webhook_data.get(
            "pull_request",
            {},
        ).get("number")

        installation_id = webhook_data.get(
            "installation",
            {},
        ).get("id")

        # =====================================================================
        # STEP 7: Make sure required information exists
        # =====================================================================

        logger.info(
            "PR event detected: action=%s, repo=%s, pr=%s, installation=%s",
            action,
            repository_name,
            pull_request_number,
            installation_id,
        )

        if (
            pull_request_number
            and repository_name
            and installation_id
        ):

            # =============================================================
            # STEP 8: Extract account type from installation
            # =============================================================

            account_type = (
                webhook_data
                .get("installation", {})
                .get("account", {})
                .get("type", "Organization")
            )

            # =============================================================
            # STEP 8.5: Is the App still installed & active for this repo?
            # =============================================================

            if not await _installation_active(installation_id):
                logger.info(
                    "Skipping review of %s#%d — installation %s is "
                    "suspended or removed.",
                    repository_name,
                    pull_request_number,
                    installation_id,
                )
            else:
                logger.info(
                    "Starting background review for %s#%d "
                    "(installation %d, account_type=%s)",
                    repository_name,
                    pull_request_number,
                    installation_id,
                    account_type,
                )

                # =========================================================
                # STEP 9: Start the review in the background (de-duplicated)
                # =========================================================

                _schedule_review(
                    installation_id=installation_id,
                    repo_full_name=repository_name,
                    pr_number=pull_request_number,
                    account_type=account_type,
                )

        else:

            logger.warning(
                "Cannot start review because required "
                "webhook information is missing: "
                "pr_number=%s, repository=%s, installation_id=%s",
                pull_request_number,
                repository_name,
                installation_id,
            )

    elif x_github_event in ("installation", "installation_repositories"):
        # =====================================================================
        # App lifecycle — keep the installation row in sync
        # =====================================================================
        try:
            await _handle_installation_event(x_github_event, action, webhook_data)
        except Exception as error:
            logger.error("Failed handling %s event: %s", x_github_event, error)

    else:
        # =====================================================================
        # Event does not trigger a review
        # =====================================================================

        logger.info(
            "Webhook event does not trigger review: "
            "event=%s, action=%s (only pull_request.opened "
            "and pull_request.synchronize trigger reviews)",
            x_github_event,
            action,
        )

    # =========================================================================
    # STEP 9: Immediately respond to GitHub
    # =========================================================================

    return {
        "status": "success",
        "event": x_github_event,
        "action": action,
        "repository": repository_name,
        "sender": sender_username,
    }


# ============================================================================
# INSTALLATION LIFECYCLE
# ============================================================================


async def _handle_installation_event(
    event: str, action: str | None, payload: dict
) -> None:
    """Keep `github_installations` in sync with App install/uninstall/suspend.

    Records the installer's GitHub id and links the row to a PRGuard user
    if one already exists for that GitHub account (otherwise it is linked
    on that user's next login via reconcile_installations()).
    """
    from datetime import datetime, timezone

    from app.core.database import AsyncSessionLocal
    from app.github.app_auth import invalidate_token_cache
    from app.repositories.installation_repo import InstallationRepository
    from app.repositories.user_repo import UserRepo

    inst = payload.get("installation", {}) or {}
    installation_id = inst.get("id")
    if not installation_id:
        return

    account = inst.get("account", {}) or {}
    account_name = account.get("login", f"installation-{installation_id}")
    account_type = account.get("type", "User")
    account_id = account.get("id")
    installer_github_id = (payload.get("sender", {}) or {}).get("id")

    from app.api.github_app import _sync_installation_repos

    async with AsyncSessionLocal() as session:
        repo = InstallationRepository(session)

        # If we already know this GitHub user (installer or personal-account
        # owner), link the installation to them now.
        linked_user_id = None
        for gh_id in (installer_github_id, account_id):
            if gh_id:
                u = await UserRepo(session).get_by_github_id(gh_id)
                if u:
                    linked_user_id = u.id
                    break

        if event == "installation" and action in ("created", "unsuspend", "new_permissions_accepted"):
            await repo.upsert(
                installation_id=installation_id,
                account_name=account_name,
                account_type=account_type,
                account_id=account_id,
                installer_github_id=installer_github_id,
                user_id=linked_user_id,
                clear_deleted=(action != "new_permissions_accepted"),
            )
            await _sync_installation_repos(session, installation_id)
        elif event == "installation" and action == "deleted":
            existing = await repo.get_by_installation_id(installation_id)
            if existing:
                await repo.mark_deleted(existing)
            invalidate_token_cache(installation_id)
        elif event == "installation" and action == "suspend":
            existing = await repo.get_by_installation_id(installation_id)
            if existing:
                await repo.update(
                    existing, suspended_at=datetime.now(timezone.utc)
                )
        else:
            # installation_repositories added/removed — ensure the row
            # exists, then re-sync the repo list.
            await repo.upsert(
                installation_id=installation_id,
                account_name=account_name,
                account_type=account_type,
                account_id=account_id,
            )
            await _sync_installation_repos(session, installation_id)

        await session.commit()
        logger.info(
            "Installation %s: %s.%s → synced", installation_id, event, action
        )


# ============================================================================
# BACKGROUND REVIEW TASK
# ============================================================================


async def run_review_in_background(
    installation_id: int,
    repo_full_name: str,
    pr_number: int,
    account_type: str = "Organization",
) -> None:
    """
    Run the PRGuard review pipeline in the background.

    This function calls the main review worker.

    Keeping this logic separate from the webhook endpoint makes the
    webhook handler easier to understand.

    Args:
        installation_id:
            GitHub App installation ID.

        repo_full_name:
            Repository name in the format "owner/repository".

        pr_number:
            Pull request number.

        account_type:
            GitHub account type ("User" or "Organization").
            Extracted from the webhook payload.

    Returns:
        None
    """

    try:

        # Import here to avoid circular imports.
        from app.workers.review_worker import run_review

        async with _get_review_semaphore():
            await run_review(
                installation_id=installation_id,
                repo_full_name=repo_full_name,
                pr_number=pr_number,
                account_type=account_type,
            )

    except Exception as error:

        logger.error(
            "Background review failed for %s#%d: %s",
            repo_full_name,
            pr_number,
            error,
            exc_info=True,
        )