"""add review phase tracking

Revision ID: 10f1462f8a86
Revises: e49f85348ad5
Create Date: 2026-09-03 02:00:34.041557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f1462f8a86'
down_revision: Union[str, Sequence[str], None] = 'e49f85348ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('current_phase', sa.String(length=100), nullable=True))
    op.add_column('reviews', sa.Column('phase_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'phase_message')
    op.drop_column('reviews', 'current_phase')
    # ### end Alembic commands ###
