"""review head_sha + finding validation fields

Revision ID: 8b949b5fa9e1
Revises: 10f1462f8a86
Create Date: 2026-09-03 17:34:33.557968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b949b5fa9e1'
down_revision: Union[str, Sequence[str], None] = '10f1462f8a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('validation_status', sa.String(length=50), nullable=True))
    op.add_column('findings', sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('findings', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('reviews', sa.Column('head_sha', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###

    # Backfill: existing reviews inherit their pull request's current head_sha
    # so they are still matchable for reuse.
    op.execute(
        """
        UPDATE reviews r
        SET head_sha = pr.head_sha
        FROM pull_requests pr
        WHERE r.pull_request_id = pr.id
          AND r.head_sha IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'head_sha')
    op.drop_column('findings', 'is_published')
    op.drop_column('findings', 'validation_notes')
    op.drop_column('findings', 'validation_status')
    # ### end Alembic commands ###
