"""github oauth users

Revision ID: e85d47b39c19
Revises: 92fa37e89485
Create Date: 2026-09-04 00:13:12.431895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85d47b39c19'
down_revision: Union[str, Sequence[str], None] = '92fa37e89485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Switching from email/password to GitHub OAuth. Existing rows have no
    # GitHub identity — clear them (installations keep their rows, their
    # user_id is set NULL by the FK and re-linked on the user's next login).
    op.execute("DELETE FROM users")

    op.add_column('github_installations', sa.Column('installer_github_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('github_user_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['github_user_id'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'github_user_id')
    op.drop_column('github_installations', 'installer_github_id')
    # ### end Alembic commands ###
